### ISSUE TITLE
Exception thrown from Hopac

### ISSUE THREAD

**Issue by simax** [relentless/Http.fs#169]
I've just started playing with this library (thank you for your hard work btw) and noticed that it seems throw an exception if I try to hit a Url that includes a port number.

e.g. If I use this simple code

```
    job {
        let request =
            url
            |> Request.createUrl Get
            |> Request.setHeader (Accept "application/json")
            |> Request.setHeader (Authorization("Bearer " + token))

        let! response = getResponse request
        match response.statusCode with
        | 200 ->
            let! bodyStr = Response.readBodyAsString response
            return (response.statusCode, bodyStr)
        | _ -> return (response.statusCode, "")
    }
```

and try to hit something like ```http://localhost:8089/some/url/```. If there is nothing running on that port I get the following exception from the line ```let! response = getResponse request``` . I'm purposely trying to hit something that doesn't exist in order to simulate hitting an API that's down for some reason.

I only mention it because [this comment on this issue](https://github.com/haf/Http.fs/issues/103#issuecomment-241496718) states that ```Http.fs``` shouldn't throw exceptions (even though the exception originates in ```Hopac```) 

I was hoping it wouldn't throw an exception but give me  back a status code that I could pattern match on. Maybe I'm doing something wrong?

**Comment by haf** [comment]
Thanks for reporting. What is the exception thrown?

**Comment by simax** [comment]
Apologies, silly of me not to have shown the exception that gets thrown. This is it: 

```
Exception has occurred: CLR/System.Exception
An unhandled exception of type 'System.Exception' occurred in Hopac.dll: 'Exception raised by job'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.ConnectHelper.<ConnectAsync>d__1.MoveNext()
```

**Comment by haf** [comment]
Yes you are right. I have an updated version available but I need a maintainer to do the integration and documentation; if you have a time budget for it, you can have the code if you make it into a PR

**Comment by simax** [comment]
I'm struggling for time for the next few weeks but beyond that I could give it a go. I've never contributed to an OSS project before so I'll need to come back to you then and get more detail on what would be involved. I would like to give something back.

**Comment by haf** [comment]
You could use `tryGetResponse` and it should be caught. — might be quicker in this case ;)

https://github.com/haf/Http.fs/blob/b1bd152c256d17be924a8f975a67e2f4200ee343/HttpFs/HttpFs.fs#L988
